#pragma once

#include <glaze/util/string_literal.hpp>
#include "col.hpp"

namespace glz_sqlgen::literals {

/// Column literal operator: "name"_c creates Col<"name">
template <glz::string_literal Name>
constexpr auto operator""_c() {
    return Col<Name>{};
}

/// Table alias literal operators: "name"_t1 creates Col<"name", "t1">
#define GLZ_SQLGEN_TABLE_ALIAS_LITERAL(N)           \
    template <glz::string_literal Name>             \
    constexpr auto operator""_t##N() {              \
        return Col<Name, "t" #N>{};                 \
    }

GLZ_SQLGEN_TABLE_ALIAS_LITERAL(1)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(2)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(3)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(4)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(5)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(6)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(7)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(8)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(9)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(10)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(11)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(12)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(13)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(14)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(15)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(16)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(17)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(18)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(19)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(20)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(21)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(22)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(23)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(24)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(25)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(26)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(27)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(28)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(29)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(30)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(31)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(32)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(33)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(34)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(35)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(36)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(37)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(38)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(39)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(40)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(41)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(42)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(43)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(44)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(45)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(46)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(47)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(48)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(49)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(50)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(51)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(52)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(53)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(54)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(55)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(56)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(57)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(58)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(59)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(60)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(61)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(62)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(63)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(64)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(65)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(66)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(67)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(68)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(69)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(70)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(71)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(72)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(73)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(74)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(75)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(76)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(77)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(78)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(79)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(80)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(81)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(82)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(83)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(84)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(85)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(86)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(87)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(88)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(89)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(90)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(91)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(92)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(93)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(94)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(95)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(96)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(97)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(98)
GLZ_SQLGEN_TABLE_ALIAS_LITERAL(99)

#undef GLZ_SQLGEN_TABLE_ALIAS_LITERAL

} // namespace glz_sqlgen::literals
